Small improvement

diff --git a/mass-git b/mass-git
--- a/mass-git
+++ b/mass-git
@@ -3,7 +3,7 @@
 # Fetch or pull one or more git repositories at a specified location on your system.
 #
 # License: MIT License
-#          Copyright (c) 2021-2022 Hunter T. (StrangeRanger)
+#          Copyright (c) 2021-2024 Hunter T. (StrangeRanger)
 #
 ########################################################################################
 #### [ Variables ]
@@ -31,9 +31,9 @@ git_action_prog="Pulling"
 usage() {
     echo "Fetch or pull one or more git repositories at a specified location on your system."
     echo ""
-    echo "Usage: ./${0##*/} [-r] [-f] [-d] -p <path>"
-    echo "       ./${0##*/} -h"
-    echo "       ./${0##*/} -v"
+    echo "Usage: ${0##*/} [-r] [-f] [-d] -p <path>"
+    echo "       ${0##*/} -h"
+    echo "       ${0##*/} -v"
     echo ""
     echo "Options:"
     echo "  -h, --help       : Displays this help message."
@@ -67,22 +67,10 @@ while [[ -n $1 ]]; do
             shift
 
             if hash realpath; then
-                path="$(realpath "$1")"
+                path="$(realpath "$1" 2>/dev/null || echo "BAD MAGIC")"
             else
-                ####
-                # EXPLANATION:
-                #   1. Gets the relative path as argument `"$1"`
-                #   2. Gets the dirname part of that path: `dirname "$1"`
-                #   3. `cd "$(dirname "$1")` into the relative dir and get the absolute
-                #      path for it by running `pwd`
-                #   4. Append the basename to the absolute path: `$(basename "$1")`
-                #
                 # This solution was found at the following link:
                 # https://stackoverflow.com/questions/4175264/how-to-retrieve-absolute-path-given-relative/31605674#31605674
-                #
-                # '|| exit' makes sure that if the script is unable to change
-                # directories, the script is exitted.
-                ####
                 path="$(cd "${1%/*}" || exit; pwd)/${1##*/}"
             fi
             provided_path=true
@@ -111,13 +99,11 @@ done
 
 ## Check if the provided path is a valid directory.
 if "$provided_path"; then
-    if [[ ! -d $path ]]; then
-        if [[ -f $path ]]; then
-            echo "${red}Invalid input:${nc} File was provided when a directory was" \
-                "expected" >&2
-        else
-            echo "${red}Invalid input:${nc} Directory does not exist" >&2
-        fi
+    if [[ -f $path ]]; then
+        echo "${red}Invalid input:${nc} File was provided when a directory was expected" >&2
+        exit 1
+    elif [[ ! -d $path ]]; then
+        echo "${red}Invalid input:${nc} Directory does not exist" >&2
         exit 1
     fi
 else
@@ -132,7 +118,6 @@ fi
 
 
 ## Store the location of all local repositories found.
-## NOTE: $maxdepth is purposefully unquoted. Do not quote it!
 # shellcheck disable=SC2086
 while read -r -d $'\0'; do
     git_repos+=("${REPLY/%.git/}")
@@ -140,8 +125,8 @@ done < <(find "$path" $maxdepth -type d -name ".git" -prune -print0)
 
 # If no local repositories were found...
 # NOTE: Leave $git_repos as is. It's fine that only the first index of the array is
-#       provided, as all we are trying to do is confirm whether or not a git initialized
-#       directory was located.
+#       provided, as all I'm are trying to do is confirm whether or not a git
+#       initialized directory was located.
 # shellcheck disable=SC2128
 if [[ -z $git_repos ]]; then
     echo "${red}ERROR:${nc} No git initialized directory could be found"
@@ -159,7 +144,6 @@ for repo_path in "${git_repos[@]}"; do
     repo_name="$(git config --get remote.origin.url)"
 
     echo "${blue}==>${nc} $git_action_prog changes from '$repo_name'..."
-    ## NOTE: $dry_run is purposefully unquoted. Do not quote it!
     # shellcheck disable=SC2086
     git "$git_action" $dry_run \
         || echo "${red}ERROR:${nc} Failed to $git_action changes from '$repo_name'"
