Modify style and format of constant variables

diff --git a/mass-git b/mass-git
--- a/mass-git
+++ b/mass-git
@@ -6,28 +6,44 @@
 #          Copyright (c) 2021-2024 Hunter T. (StrangeRanger)
 #
 ########################################################################################
-#### [ Variables ]
+####[ Variables ]#######################################################################
 
 
-green="$(printf '\033[0;32m')"
-blue="$(printf '\033[0;34m')"
-cyan="$(printf '\033[0;36m')"
-red="$(printf '\033[1;31m')"
-nc="$(printf '\033[0m')"
+## ANSI color codes.
+C_GREEN="$(printf '\033[0;32m')"
+C_BLUE="$(printf '\033[0;34m')"
+C_CYAN="$(printf '\033[0;36m')"
+C_RED="$(printf '\033[1;31m')"
+C_NC="$(printf '\033[0m')"
 
-version="v1.2.0"        # Program version.
+## Shorthanded variables for colorized output.
+C_INVALID_INPUT="${C_RED}Invalid input:${C_NC} "
+C_SUCCESS="${C_GREEN}==>${C_NC} "
+C_ERROR="${C_RED}ERROR:${C_NC} "
+C_INFO="${C_BLUE}==>${C_NC} "
+C_NOTE="${C_CYAN}==>${C_NC} "
+
+## Program information.
+C_VERSION="v1.2.0"
+
+## Set constants as readonly.
+readonly C_GREEN C_BLUE C_CYAN C_RED C_NC
+readonly C_INVALID_INPUT C_SUCCESS C_ERROR C_INFO C_NOTE
+readonly C_VERSION
+
+## Other variables.
 maxdepth="-maxdepth 2"  # Peform recursive searches with a maximum depth of 2.
-provided_path=false     # Validates that a path was provided.
-git_repos=()            # List of paths to existing repositories on the system.
+provided_path=false  # Validates that a path was provided.
+git_repos=()  # List of paths to existing repositories on the system.
 git_action="pull"
 git_action_prog="Pulling"
 
 
-#### End of [ Variables ]
-########################################################################################
-#### [ Functions ]
+####[ Functions ]#######################################################################
 
 
+####
+# Display the usage message for the program.
 usage() {
     echo "Fetch or pull one or more git repositories at a specified location on your system."
     echo ""
@@ -45,9 +61,7 @@ usage() {
 }
 
 
-#### End of [ Functions ]
-########################################################################################
-#### [ Options ]
+####[ Options ]#########################################################################
 
 
 # If no arguments are provided...
@@ -86,11 +100,11 @@ while [[ -n $1 ]]; do
             dry_run="--dry-run"
             ;;
         "-v"|"--version")
-            echo "Mass Git $version"
+            echo "Mass Git $C_VERSION"
             exit 0
             ;;
         *)
-            echo "${red}Invalid option:${nc} $1" >&2
+            echo "${C_RED}Invalid option:${C_NC} $1" >&2
             exit 1
             ;;
     esac
@@ -100,21 +114,19 @@ done
 ## Check if the provided path is a valid directory.
 if "$provided_path"; then
     if [[ -f $path ]]; then
-        echo "${red}Invalid input:${nc} File was provided when a directory was expected" >&2
+        echo "${C_INVALID_INPUT}File was provided when a directory was expected" >&2
         exit 1
     elif [[ ! -d $path ]]; then
-        echo "${red}Invalid input:${nc} Directory does not exist" >&2
+        echo "${C_INVALID_INPUT}Directory does not exist" >&2
         exit 1
     fi
 else
-    echo "${red}Invalid input:${nc} Missing required argument '-p <path>'"
+    echo "${C_INVALID_INPUT}Missing required argument '-p <path>'"
     exit 1
 fi
 
 
-#### End of [ Options ]
-########################################################################################
-#### [ Main ]
+####[ Main ]############################################################################
 
 
 ## Store the location of all local repositories found.
@@ -129,28 +141,25 @@ done < <(find "$path" $maxdepth -type d -name ".git" -prune -print0)
 #       initialized directory was located.
 # shellcheck disable=SC2128
 if [[ -z $git_repos ]]; then
-    echo "${red}ERROR:${nc} No git initialized directory could be found"
+    echo "${C_ERROR}No git initialized directory could be found"
     exit 1
 fi
 
-[[ $dry_run = "--dry-run" ]] && echo "${cyan}==>${nc} Performing a dry-run..."
+[[ $dry_run = "--dry-run" ]] && echo "${C_NOTE}Performing a dry-run..."
 
 for repo_path in "${git_repos[@]}"; do
-    echo "${blue}==>${nc} Changing directories to '$repo_path'..."
+    echo "${C_INFO}Changing directories to '$repo_path'..."
     cd "$repo_path" || {
-        echo "${red}ERROR:${nc} Failed to change directories"
+        echo "${C_ERROR}Failed to change directories"
         exit 1
     }
     repo_name="$(git config --get remote.origin.url)"
 
-    echo "${blue}==>${nc} $git_action_prog changes from '$repo_name'..."
+    echo "${C_INFO}$git_action_prog changes from '$repo_name'..."
     # shellcheck disable=SC2086
     git "$git_action" $dry_run \
-        || echo "${red}ERROR:${nc} Failed to $git_action changes from '$repo_name'"
+        || echo "${C_ERROR}Failed to $git_action changes from '$repo_name'"
 done
 
-echo "${green}==>${nc} Done"
+echo "${C_SUCCESS}Done"
 
-
-#### End of [ Main ]
-########################################################################################
